<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"><channel><title>MariaDB Knowledge Base Comments for: Please help with calling a MariaDB procedure from MSAccess</title><link>https://mariadb.com/kb/en/please-help-with-calling-a-mariadb-procedure-from-msaccess/+comments/feed/</link><description></description><atom:link href="https://mariadb.com/kb/en/please-help-with-calling-a-mariadb-procedure-from-msaccess/+comments/feed/" rel="self"></atom:link><language>en-us</language><lastBuildDate>Tue, 23 Jan 2024 00:56:27 +0000</lastBuildDate><item><title>Re: Please help with calling a MariaDB procedure from MSAccess</title><link>https://mariadb.com/kb/en/please-help-with-calling-a-mariadb-procedure-from-msaccess/+comments/4590</link><description>&lt;p&gt;Correction. The same procedure that runs just fine when I call it from the workbench is claimed "not found" when using a connector string with the same user and credentials through python. So this is not an ODBC issue.&lt;/p&gt;
</description><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Ingo Korndoerfer</dc:creator><guid>https://mariadb.com/kb/en/please-help-with-calling-a-mariadb-procedure-from-msaccess/+comments/4590</guid></item></channel></rss>